spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/report?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: pmb@123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      auto-commit: true
      pool-name: MyBootHikariDataPool
      connection-timeout: 30000

data:
  trans:
    path: /tmp/xdcs/report/西电财务公司/利率报备
  gen:
    path: /tmp/xdcs/report/西电财务公司/人行报文