spring:
  application:
    name: regulatory-report
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sdjictec.xdfin.regulatory.report.entity

logging:
  level:
    root: info
    com.sdjictec.xdfin.regulatory: debug
server:
  port: 8099